package simtest

import (
	"context"
	"fmt"
	"sort"

	"github.com/sorotrail/sorotrail/internal/store"
)

// Oracle verifies that stored events match the set of fetchable chain events
// after a simulation scenario completes.
//
// # Fetchability predicate
//
// An event E at ledger L is \"fetchable\" iff all of the following hold
// throughout the simulation:
//
//  1. E was generated (exists in the chain's event set).
//  2. L was within the RPC retention window at the moment the ingester
//     attempted to fetch it. In the simulation, the retention window is
//     [LatestLedger - RetentionLedgers, LatestLedger] at the time of the
//     GetEvents call that would have covered L.
//  3. The ingester was running (not crashed) when L was in range.
//  4. No fault prevented the RPC from returning E — retries after a fault
//     count as the ingester having attempted; the event is still fetchable
//     if a subsequent attempt succeeded.
//  5. E was not in a ledger range that the ingester intentionally skipped
//     via reclampToOldest (logged as \"skipping ahead — events in the gap
//     are lost\"). These are legitimately lost and must NOT be in the store.
//
// # Oracle assertions
//
// After each scenario the oracle checks:
//   - Every fetchable event exists in the store exactly once.
//   - No events exist in the store that were not generated by the chain.
//   - Events legitimately lost to retention gaps are NOT in the store.
//   - The ingester warned about each legitimate gap.
//
// # Implementation note
//
// The oracle computes the set of legitimately lost ledgers by tracking
// calls to reclampToOldest. In the simulation, when a GetEvents call
// returns an out-of-range error and the ingester re-clamps, we record the
// gap [requested, oldestRetained-1] as legitimately lost.
type Oracle struct {
	// chain has all generated events.
	chain *VirtualChain

	// legitimatelyLost is the set of ledger ranges the ingester
	// intentionally skipped.
	legitimatelyLost []ledgerRange

	// warnings is the count of reclamp warnings.
	warnings int
}

// ledgerRange is a closed interval [from, to].
type ledgerRange struct {
	from, to uint32
}

// NewOracle creates an oracle backed by the given chain.
func NewOracle(chain *VirtualChain) *Oracle {
	return &Oracle{chain: chain}
}

// RecordReclamp records that the ingester skipped [requested, oldest)
// as a legitimate gap. Called when an out-of-range error triggers
// reclampToOldest.
func (o *Oracle) RecordReclamp(requested, oldest uint32) {
	if requested >= oldest {
		return // no actual gap
	}
	o.legitimatelyLost = append(o.legitimatelyLost, ledgerRange{
		from: requested,
		to:   oldest - 1,
	})
	o.warnings++
}

// DrainGaps consumes all out-of-range gaps recorded by the chain and
// registers them as legitimately lost ledgers.
func (o *Oracle) DrainGaps() {
	for _, gap := range o.chain.OutOfRangeGaps() {
		o.RecordReclamp(gap.requested, gap.oldest)
	}
}

// Verify checks that the store contains exactly the fetchable events.
// It returns an error describing the first mismatch found, or nil.
func (o *Oracle) Verify(ctx context.Context, st store.Store) error {
	chainEvents := o.chain.EngineEvents()

	// Compute the set of legitimately lost ledger ranges efficiently.
	lostSet := make(map[uint32]bool)
	for _, lr := range o.legitimatelyLost {
		for l := lr.from; l <= lr.to; l++ {
			lostSet[l] = true
		}
	}

	// Determine which events are fetchable.
	fetchable := make(map[string]bool)
	for _, ce := range chainEvents {
		if lostSet[ce.Ledger] {
			continue // legitimately lost
		}
		// If the ledger was within the retention window at any point during
		// the simulation, it was fetchable. The chain model ensures that
		// events are only returned by GetEvents if they are in range, so
		// we trust the chain's generation.
		fetchable[ce.Event.ID] = true
	}

	// Query all stored events. We use a high limit to get everything.
	stored, _, err := st.QueryEvents(ctx, store.EventFilter{Limit: 100000, Order: "asc"})
	if err != nil {
		return fmt.Errorf("querying stored events: %w", err)
	}

	// Build set of stored IDs and check for duplicates.
	storedIDs := make(map[string]int)
	for _, ev := range stored {
		storedIDs[ev.ID]++
	}

	// Check 1: every fetchable event is stored exactly once.
	for id := range fetchable {
		count := storedIDs[id]
		if count == 0 {
			return fmt.Errorf("fetchable event %s is missing from the store", id)
		}
		if count > 1 {
			return fmt.Errorf("fetchable event %s appears %d times in the store (expected 1)", id, count)
		}
	}

	// Check 2: no spurious events in the store.
	// Legitimate-loss gaps record the RPC's refusal to serve a range, but
	// events already persisted before the gap occurred are fine — they were
	// ingested during an earlier, successful pass and are not truly "lost."
	for id, count := range storedIDs {
		if !fetchable[id] {
			// If the event's ledger is in a lost range, it's tolerated:
			// the gap was reported by the RPC after some events were
			// already safely persisted.
			inLostRange := false
			for _, ce := range chainEvents {
				if ce.Event.ID == id && lostSet[ce.Ledger] {
					inLostRange = true
					break
				}
			}
			if !inLostRange {
				return fmt.Errorf("spurious event %s in store (not in chain)", id)
			}
			// Event in lost range but already persisted: not an error.
		}
		_ = count
	}

	// Check 3: verify warning count matches actual gaps.
	// If there were legitimate gaps, the ingester must have warned.
	if len(o.legitimatelyLost) > 0 && o.warnings == 0 {
		return fmt.Errorf("events were legitimately lost but no reclamp warnings were recorded (silent data loss)")
	}

	return nil
}

// FetchableCount returns the number of events the ingester should have
// captured in this scenario.
func (o *Oracle) FetchableCount() int {
	chainEvents := o.chain.EngineEvents()
	lostSet := make(map[uint32]bool)
	for _, lr := range o.legitimatelyLost {
		for l := lr.from; l <= lr.to; l++ {
			lostSet[l] = true
		}
	}
	count := 0
	for _, ce := range chainEvents {
		if !lostSet[ce.Ledger] {
			count++
		}
	}
	return count
}

// LegitimatelyLostEvents returns the IDs of events that were legitimately
// lost to retention gaps.
func (o *Oracle) LegitimatelyLostEvents() []string {
	chainEvents := o.chain.EngineEvents()
	lostSet := make(map[uint32]bool)
	for _, lr := range o.legitimatelyLost {
		for l := lr.from; l <= lr.to; l++ {
			lostSet[l] = true
		}
	}
	var lost []string
	for _, ce := range chainEvents {
		if lostSet[ce.Ledger] {
			lost = append(lost, ce.Event.ID)
		}
	}
	sort.Strings(lost)
	return lost
}

// StoredCount returns how many events are currently in the store.
func (o *Oracle) StoredCount(ctx context.Context, st store.Store) (int, error) {
	events, _, err := st.QueryEvents(ctx, store.EventFilter{Limit: 100000, Order: "asc"})
	if err != nil {
		return 0, err
	}
	return len(events), nil
}
