package simtest

import (
	"fmt"
	"math/rand/v2"
	"time"
)

// RandomScenario generates a random scenario with the given seed for
// deterministic reproduction. The seed is printed on failure and can be
// passed back to RandomScenario to replay the exact fault schedule.
//
// The generator:
//   - Picks random retention window (10-500 ledgers)
//   - Generates 5-50 events at random ledgers
//   - Injects 0-3 random faults (timeout, out-of-range, rate-limit)
//   - Optionally triggers a crash
func RandomScenario(seed uint64) Scenario {
	rng := rand.New(rand.NewPCG(seed, seed>>32))
	return generateRandom(rng, fmt.Sprintf("random_%d", seed))
}

// generateRandom produces a scenario using the given RNG.
func generateRandom(rng *rand.Rand, name string) Scenario {
	numEvents := 5 + rng.IntN(46) // 5-50 events
	maxLedger := uint32(20 + rng.IntN(200))
	retention := uint32(10 + rng.IntN(491)) // 10-500

	events := make([]EventPlacement, numEvents)
	for i := range events {
		events[i] = EventPlacement{
			Ledger:     uint32(1 + rng.IntN(int(maxLedger))),
			ContractID: "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
		}
	}

	var faults []FaultDescriptor
	numFaults := rng.IntN(4) // 0-3 faults
	for i := 0; i < numFaults; i++ {
		faultType := rng.IntN(4)
		callIdx := 1 + rng.IntN(5) // call 1-5
		switch faultType {
		case 0:
			faults = append(faults, FaultDescriptor{
				Kind: FaultTimeout, CallIndex: callIdx,
			})
		case 1:
			faults = append(faults, FaultDescriptor{
				Kind: FaultRateLimit, CallIndex: callIdx,
			})
		case 2:
			faults = append(faults, FaultDescriptor{
				Kind: FaultOutOfRange, CallIndex: callIdx,
			})
		case 3:
			if rng.IntN(2) == 0 {
				faults = append(faults, FaultDescriptor{
					Kind: FaultCrash, AfterStep: 1 + rng.IntN(5),
				})
			}
		}
	}

	return Scenario{
		Name:             name,
		Description:      "Randomized scenario generated by PRNG.",
		RetentionLedgers: retention,
		ChainLedgers:     maxLedger,
		PageLimit:        uint(10 + rng.IntN(90)),
		Events:           events,
		Faults:           faults,
	}
}

// RandomScenarioWithTime generates a random scenario seeded from the current
// time. The seed is returned so it can be reproduced on failure.
func RandomScenarioWithTime() (Scenario, uint64) {
	seed := uint64(time.Now().UnixNano())
	return RandomScenario(seed), seed
}
